/* ===================================================================
   Sigma Infotech — Product Data Layer
   All product data lives here so it can be easily replaced with
   API/database calls in the future.
   =================================================================== */

export const PRODUCTS = {
  'dell-latitude-7490': {
    brand: 'Dell · Latitude Series',
    title: 'Dell Latitude 7490 — 14" Business Laptop',
    grade: 'Excellent',
    gradeClass: '',
    price: '₹19,999',
    priceOld: '₹22,999',
    desc: 'Lightweight business laptop, fully cleaned, tested and re-certified by our technicians. Battery, keyboard and display checked for full working condition before listing.',
    icon: 'laptop',
    specs: [
      ['Processor', 'Intel Core i5-8350U (8th Gen)'],
      ['RAM', '8GB DDR4'],
      ['Storage', '256GB SSD'],
      ['Display', '14" FHD (1920×1080)'],
      ['Graphics', 'Intel UHD 620 (Integrated)'],
      ['Battery Health', 'Tested — holds charge normally'],
      ['Condition Grade', 'Excellent — minimal cosmetic wear'],
      ['Included', 'Original charger, cleaned chassis'],
    ],
  },
  'hp-elitebook-840-g5': {
    brand: 'HP · EliteBook Series',
    title: 'HP EliteBook 840 G5 — 14" Business Laptop',
    grade: 'Good',
    gradeClass: 'grade-good',
    price: '₹21,499',
    priceOld: '₹24,499',
    desc: 'Reliable business laptop, fully cleaned, tested and re-certified by our technicians. Battery, keyboard and display checked for full working condition before listing.',
    icon: 'laptop',
    specs: [
      ['Processor', 'Intel Core i5-8250U (8th Gen)'],
      ['RAM', '8GB DDR4'],
      ['Storage', '512GB SSD'],
      ['Display', '14" FHD (1920×1080)'],
      ['Graphics', 'Intel UHD 620 (Integrated)'],
      ['Battery Health', 'Tested — good capacity'],
      ['Condition Grade', 'Good — light cosmetic wear'],
      ['Included', 'Original charger'],
    ],
  },
  'lenovo-thinkpad-t480': {
    brand: 'Lenovo · ThinkPad Series',
    title: 'Lenovo ThinkPad T480 — 14" Business Laptop',
    grade: 'Excellent',
    gradeClass: '',
    price: '₹26,999',
    priceOld: '₹30,999',
    desc: 'High-spec business laptop, fully cleaned, tested and re-certified by our technicians. Battery, keyboard and display checked for full working condition before listing.',
    icon: 'laptop',
    specs: [
      ['Processor', 'Intel Core i7-8550U (8th Gen)'],
      ['RAM', '16GB DDR4'],
      ['Storage', '512GB SSD'],
      ['Display', '14" FHD (1920×1080)'],
      ['Graphics', 'Intel UHD 620 (Integrated)'],
      ['Battery Health', 'Tested — holds charge normally'],
      ['Condition Grade', 'Excellent — minimal cosmetic wear'],
      ['Included', 'Original charger, cleaned chassis'],
    ],
  },
  'acer-aspire-5': {
    brand: 'Acer · Aspire Series',
    title: 'Acer Aspire 5 — 15.6" Everyday Laptop',
    grade: 'Fair',
    gradeClass: 'grade-fair',
    price: '₹12,999',
    priceOld: '₹15,499',
    desc: 'Budget-friendly everyday laptop, fully cleaned and tested by our technicians. Ideal for browsing, office work and study use.',
    icon: 'laptop',
    specs: [
      ['Processor', 'Intel Core i3-7100U (7th Gen)'],
      ['RAM', '4GB DDR4'],
      ['Storage', '500GB HDD'],
      ['Display', '15.6" HD (1366×768)'],
      ['Graphics', 'Intel HD 620 (Integrated)'],
      ['Battery Health', 'Tested — reduced capacity'],
      ['Condition Grade', 'Fair — visible cosmetic wear'],
      ['Included', 'Charger'],
    ],
  },
  'dell-optiplex-7050-sff': {
    brand: 'Dell · OptiPlex Series',
    title: 'Dell OptiPlex 7050 SFF — Desktop Tower',
    grade: 'Good',
    gradeClass: 'grade-good',
    price: '₹17,999',
    priceOld: '₹20,999',
    desc: 'Compact small-form-factor desktop, fully cleaned, tested and re-certified by our technicians. Great for home or office use.',
    icon: 'desktop',
    specs: [
      ['Processor', 'Intel Core i5-6500'],
      ['RAM', '8GB DDR4'],
      ['Storage', '256GB SSD'],
      ['Form Factor', 'Small Form Factor (SFF)'],
      ['Graphics', 'Intel HD 530 (Integrated)'],
      ['Condition Grade', 'Good — light cosmetic wear'],
      ['Included', 'Power cable (monitor/keyboard/mouse sold separately)'],
    ],
  },
  'hp-prodesk-600-g4': {
    brand: 'HP · ProDesk Series',
    title: 'HP ProDesk 600 G4 — Desktop Tower',
    grade: 'Excellent',
    gradeClass: '',
    price: '₹24,999',
    priceOld: '₹28,999',
    desc: 'High-performance small-form-factor desktop, fully cleaned, tested and re-certified by our technicians.',
    icon: 'desktop',
    specs: [
      ['Processor', 'Intel Core i7-8700'],
      ['RAM', '16GB DDR4'],
      ['Storage', '512GB SSD'],
      ['Form Factor', 'Small Form Factor (SFF)'],
      ['Graphics', 'Intel UHD 630 (Integrated)'],
      ['Condition Grade', 'Excellent — minimal cosmetic wear'],
      ['Included', 'Power cable (monitor/keyboard/mouse sold separately)'],
    ],
  },
  'canon-pixma-g2010': {
    brand: 'Canon · PIXMA Series',
    title: 'Canon PIXMA G2010 — Ink Tank Printer',
    grade: 'Good',
    gradeClass: 'grade-good',
    price: '₹4,499',
    priceOld: '₹5,999',
    desc: 'Ink tank printer with print and scan, tested by our technicians for smooth ink flow and clean output.',
    icon: 'printer',
    specs: [
      ['Type', 'Ink tank (print & scan)'],
      ['Connectivity', 'USB'],
      ['Print Speed', 'Up to 8.8 ipm (mono)'],
      ['Condition Grade', 'Good — tested ink system'],
      ['Included', 'Power cable, USB cable'],
    ],
  },
  'hp-laserjet-p1102': {
    brand: 'HP · LaserJet Series',
    title: 'HP LaserJet P1102 — Mono Laser Printer',
    grade: 'Fair',
    gradeClass: 'grade-fair',
    price: '₹3,199',
    priceOld: '₹4,299',
    desc: 'Compact mono laser printer, tested for print quality and reliability by our technicians.',
    icon: 'printer',
    specs: [
      ['Type', 'Mono laser (print only)'],
      ['Connectivity', 'USB'],
      ['Print Speed', 'Up to 18 ppm'],
      ['Condition Grade', 'Fair — visible cosmetic wear'],
      ['Included', 'Power cable, USB cable'],
    ],
  },
};

export const PRODUCT_ICONS = {
  laptop: '<rect x="6" y="6" width="78" height="46" rx="2"/><path d="M2 58h86l-6 8H8Z"/>',
  desktop: '<rect x="10" y="4" width="34" height="62" rx="2"/><circle cx="27" cy="14" r="2"/><rect x="50" y="30" width="34" height="24" rx="1"/><path d="M58 62h20"/>',
  printer: '<path d="M20 24V6h50v18"/><rect x="8" y="24" width="74" height="28" rx="2"/><rect x="22" y="52" width="46" height="12"/>',
};

/** Products shown on the homepage "Featured this week" section */
export const FEATURED_PRODUCTS = [
  {
    id: 'dell-latitude-7490',
    brand: 'Dell · Latitude',
    name: 'Dell Latitude 7490',
    specs: 'i5-8350U · 8GB RAM · 256GB SSD · 14"',
    price: '₹19,999',
    grade: 'Excellent',
    gradeClass: '',
  },
  {
    id: 'hp-elitebook-840-g5',
    brand: 'HP · EliteBook',
    name: 'HP EliteBook 840 G5',
    specs: 'i5-8250U · 8GB RAM · 512GB SSD · 14"',
    price: '₹21,499',
    grade: 'Good',
    gradeClass: 'grade-good',
  },
  {
    id: 'lenovo-thinkpad-t480',
    brand: 'Lenovo · ThinkPad',
    name: 'Lenovo ThinkPad T480',
    specs: 'i7-8550U · 16GB RAM · 512GB SSD · 14"',
    price: '₹26,999',
    grade: 'Excellent',
    gradeClass: '',
  },
];

/** All shop products as an array with filter metadata */
export const SHOP_PRODUCTS = [
  {
    id: 'dell-latitude-7490',
    brand: 'Dell · Latitude',
    name: 'Dell Latitude 7490',
    specs: 'i5-8350U · 8GB RAM · 256GB SSD · 14"',
    price: '₹19,999',
    priceNum: 19999,
    grade: 'Excellent',
    gradeClass: '',
    category: 'laptop',
    condition: 'excellent',
    iconType: 'laptop',
  },
  {
    id: 'hp-elitebook-840-g5',
    brand: 'HP · EliteBook',
    name: 'HP EliteBook 840 G5',
    specs: 'i5-8250U · 8GB RAM · 512GB SSD · 14"',
    price: '₹21,499',
    priceNum: 21499,
    grade: 'Good',
    gradeClass: 'grade-good',
    category: 'laptop',
    condition: 'good',
    iconType: 'laptop',
  },
  {
    id: 'lenovo-thinkpad-t480',
    brand: 'Lenovo · ThinkPad',
    name: 'Lenovo ThinkPad T480',
    specs: 'i7-8550U · 16GB RAM · 512GB SSD · 14"',
    price: '₹26,999',
    priceNum: 26999,
    grade: 'Excellent',
    gradeClass: '',
    category: 'laptop',
    condition: 'excellent',
    iconType: 'laptop',
  },
  {
    id: 'acer-aspire-5',
    brand: 'Acer · Aspire',
    name: 'Acer Aspire 5',
    specs: 'i3-7100U · 4GB RAM · 500GB HDD · 15.6"',
    price: '₹12,999',
    priceNum: 12999,
    grade: 'Fair',
    gradeClass: 'grade-fair',
    category: 'laptop',
    condition: 'fair',
    iconType: 'laptop',
  },
  {
    id: 'dell-optiplex-7050-sff',
    brand: 'Dell · OptiPlex',
    name: 'Dell OptiPlex 7050 SFF',
    specs: 'i5-6500 · 8GB RAM · 256GB SSD',
    price: '₹17,999',
    priceNum: 17999,
    grade: 'Good',
    gradeClass: 'grade-good',
    category: 'desktop',
    condition: 'good',
    iconType: 'desktop',
  },
  {
    id: 'hp-prodesk-600-g4',
    brand: 'HP · ProDesk',
    name: 'HP ProDesk 600 G4',
    specs: 'i7-8700 · 16GB RAM · 512GB SSD',
    price: '₹24,999',
    priceNum: 24999,
    grade: 'Excellent',
    gradeClass: '',
    category: 'desktop',
    condition: 'excellent',
    iconType: 'desktop',
  },
  {
    id: 'canon-pixma-g2010',
    brand: 'Canon · PIXMA',
    name: 'Canon PIXMA G2010',
    specs: 'Ink tank · Print & Scan',
    price: '₹4,499',
    priceNum: 4499,
    grade: 'Good',
    gradeClass: 'grade-good',
    category: 'printer',
    condition: 'good',
    iconType: 'printer',
  },
  {
    id: 'hp-laserjet-p1102',
    brand: 'HP · LaserJet',
    name: 'HP LaserJet P1102',
    specs: 'Mono laser · Print only',
    price: '₹3,199',
    priceNum: 3199,
    grade: 'Fair',
    gradeClass: 'grade-fair',
    category: 'printer',
    condition: 'fair',
    iconType: 'printer',
  },
];

/** Related products shown on the product detail page */
export const RELATED_PRODUCTS = [
  {
    id: 'hp-elitebook-840-g5',
    brand: 'HP · EliteBook',
    name: 'HP EliteBook 840 G5',
    specs: 'i5-8250U · 8GB RAM · 512GB SSD · 14"',
    price: '₹21,499',
    grade: 'Good',
    gradeClass: 'grade-good',
  },
  {
    id: 'lenovo-thinkpad-t480',
    brand: 'Lenovo · ThinkPad',
    name: 'Lenovo ThinkPad T480',
    specs: 'i7-8550U · 16GB RAM · 512GB SSD · 14"',
    price: '₹26,999',
    grade: 'Excellent',
    gradeClass: '',
  },
  {
    id: 'acer-aspire-5',
    brand: 'Acer · Aspire',
    name: 'Acer Aspire 5',
    specs: 'i3-7100U · 4GB RAM · 500GB HDD · 15.6"',
    price: '₹12,999',
    grade: 'Fair',
    gradeClass: 'grade-fair',
  },
];

/** Homepage category cards */
export const CATEGORIES = [
  {
    title: 'Used Laptops',
    description: 'Business & student picks',
    href: '/shop',
    linkLabel: 'Browse →',
    icon: '<rect x="3" y="4" width="18" height="12" rx="1"/><path d="M2 20h20"/>',
  },
  {
    title: 'Used Desktops',
    description: 'Tower & all-in-one',
    href: '/shop',
    linkLabel: 'Browse →',
    icon: '<rect x="4" y="3" width="16" height="12" rx="1"/><path d="M9 19h6M12 15v4"/>',
  },
  {
    title: 'Printers',
    description: 'Inkjet & laser',
    href: '/shop',
    linkLabel: 'Browse →',
    icon: '<path d="M6 9V3h12v6M6 18h12v3H6z"/><rect x="4" y="9" width="16" height="7" rx="1"/>',
  },
  {
    title: 'Repair & Service',
    description: 'Diagnostics, fixes, upgrades',
    href: '/contact',
    linkLabel: 'Book now →',
    icon: '<path d="M14 3l-8 9h6l-2 9 9-11h-6l1-7Z"/>',
  },
  {
    title: 'Accessories',
    description: 'Chargers, bags, mice',
    href: '/shop',
    linkLabel: 'Browse →',
    icon: '<rect x="3" y="14" width="18" height="4" rx="1"/><path d="M6 14v-2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v2M9 8h1M14 8h1"/>',
  },
];
